### ISSUE TITLE
yolov5-v6.1 baseline model

### ISSUE THREAD

**Issue by WangRongsheng** [zhangzhengde0225/CDNet#3]
您好，非常感谢您所做的工作！
我在我的仓库 [CDNet-yolov5](https://github.com/WangRongsheng/CDNet-yolov5) 正在尝试利用您的数据集训练一些常用的检测模型，这项工作现在正在进行，不知道能否融入到您的 CDNet仓库的 `README.md`中，这项工作是完全基于现有的Yolov5的V6.1版本。

**Comment by zhangzhengde0225** [comment]
您好，我们进行这项工作时，采用的基准是当时最新YOLOv5的v3版本，后续的版本确实没有测试过。

**Comment by zhangzhengde0225** [comment]
您好，我们进行这项工作时，采用的基准是当时最新YOLOv5的v3版本，后续的版本没有测试过。
目前没有看到贵仓库结果与我们测试的结果的比对，不太确定用YOLOv5-v6.1替代YOLOv5-v3是否有意义。因此暂时不会把CDNet-yolov5添加到我们的README.md中。
如果贵工作进行了进一步改进，或解决了本项目还未解决的问题、或提供了本项目前未提供的内容（包括但不限于TFLite, ONNX, CoreML, TensorRT Export）等，我们很乐意包含您的工作，并邀请您PP成为CDNet的贡献者。
最后，感谢对我们工作的关注，祝好。
