### ISSUE TITLE
Marking error？

### ISSUE THREAD

**Issue by henryccl** [zhangzhengde0225/CDNet#6]
Is the marking of the fig error? Should it be SE-YOLOv5 + NST + SSVM？
![image](https://user-images.githubusercontent.com/44051761/156994862-8d24b625-16e4-479c-8690-a2d24b7f1ed1.png)

![image](https://user-images.githubusercontent.com/44051761/156995191-9cec1254-5617-4e2c-aff2-e9951e992235.png)

**Comment by zhangzhengde0225** [comment]
Oh, thanks for your meticulous view! The "SE-YOLOv5+NST+SE+SSVM" in Fig 9 is indeed wrong. The correct description is in Table 6 that you marked.
