### ISSUE TITLE
How SSVM works？

### ISSUE THREAD

**Issue by henryccl** [zhangzhengde0225/CDNet#7]
Hey！From the experimental results, we can see that SSVM greatly improves the detection accuracy，Although the flow of the algorithm is described in the text, I still do not quite understand the principle and implementation details of the algorithm.
Can you briefly describe how SSVM works? And can you recommend some reference material on SSVM?

**Comment by sususu1** [comment]
> Hey！From the experimental results, we can see that SSVM greatly improves the detection accuracy，Although the flow of the algorithm is described in the text, I still do not quite understand the principle and implementation details of the algorithm. Can you briefly describe how SSVM works? And can you recommend some reference material on SSVM?
hello, u can see the code in CDNet/scripts/post.py which explain SSVM idea clearly

**Comment by henryccl** [comment]
thank you for answer!
